name: GitHub Actions Demo
on:
  push:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Cache maven modules
        id: cache-mvn
        uses: actions/cache@v3
        env:
          cache-name: cache-mvn-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.mvn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: cd backend && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bjucps420_us-govt-todo-example
      - uses: actions/upload-artifact@v2
        with:
          name: war
          path: backend/target/todos-0.0.1-SNAPSHOT.jar
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: war
      - run: cd backend && docker build -t backend .
